# Generated by Django 3.2.16 on 2022-10-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_research_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.JSONField(blank=True, null=True, verbose_name='данные исследования врача')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_research_app.research', verbose_name='иследовавание')),
            ],
            options={
                'verbose_name': 'метки врача',
                'verbose_name_plural': 'метки врача',
            },
        ),
    ]
