# Generated by Django 3.2.16 on 2022-10-30 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_research_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_label_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='label',
            name='labels',
            field=models.JSONField(blank=True, null=True, verbose_name='данные меток врача'),
        ),
        migrations.AlterField(
            model_name='label',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_research_app.research', verbose_name='исследование'),
        ),
    ]
