# Generated by Django 3.2.16 on 2022-10-31 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_research_app', '0001_initial'),
        ('api_label_app', '0003_alter_label_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_research_app.research', verbose_name='исследование'),
        ),
    ]
